services:
  - type: web
    name: supervisor
    runtime: python
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      pip install -r backend/requirements.txt
    startCommand: python run.py
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_us57zMhqmyig@ep-ancient-poetry-ay41qr5p.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
